# Docs for .air.toml
# https://github.com/cosmtrek/air/blob/master/air_example.toml

root = "."

[build]
cmd = "task build"
full_bin = "task serve"
delay = 100
exclude_dir = ["tmp", "dist"]
exclude_file = [
  "internal/db/dbgen/db.go",
  "internal/db/dbgen/models.go",
  "static/css/style.css",
]
exclude_regex = ["_test.go", "_generated.go", ".sql.go", ".gen.go"]
include_ext = ["go", "sql", "js", "css", "json"]

[log]
main_only = true
