name: generate-logo-online

services:
  app:
    container_name: glo_app
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - "8088:8088"
    volumes:
      - ./:/app
      - glo_vol_app_ssh:/root/.ssh
      - glo_vol_app_gh:/root/.config/gh
      - glo_vol_app_go_mod_cache:/root/go/pkg/mod

volumes:
  glo_vol_app_ssh:
  glo_vol_app_gh:
  glo_vol_app_go_mod_cache: